### PR TITLE
Allow using crates other than (std/alloc/core)

### PR DESCRIPTION
**Pull request by jyn514**

### CODE REVIEW

**Comment by poliorcetics** [comment]
This is done on the most recent branch, does it work to your liking ?

**Comment by jyn514** [comment]
Yes, and it even caught a bug!

```
Error parsing option '-c' with value 'tracing-subscriber': The passed crate identifier 'tracing-subscriber' is not valid.
```

I needed to replace dashes with underscores.

**Comment by poliorcetics** [comment]
Yes I added a simple regex `^[\w_]+$` for it. I thought about adding correction for it (replacing `-` with `_`) but it seems risky

**Comment by jyn514** [comment]
>  I thought about adding correction for it (replacing - with _) but it seems risky

Maybe you could make it opt-in and show the crate it would be transformed to?

That said it was pretty easy to do myself, just `$(echo $crate | tr - _)`.

**Pull request closed without merging**
